/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three'
import { Canvas, extend, useFrame, useLoader, useThree } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations, Html, TransformControls, useHelper  } from '@react-three/drei'
import styled from 'styled-components'
import { motion } from 'framer-motion';

export default function FullScene({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Theo_all_06.glb')
  const { actions } = useAnimations(animations, group)
  const spotlight1 = useRef()
  const spotlight2 = useRef()
  const spotlight3 = useRef()
  const directionalLight = useRef()
  useHelper(spotlight1, THREE.SpotLightHelper, 'cyan')
  useHelper(spotlight2, THREE.SpotLightHelper, 'red')
  useHelper(spotlight3, THREE.SpotLightHelper, 'green')
  useHelper(directionalLight, THREE.DirectionalLightHelper, 'yellow')
  let angle = 0.1
  useFrame((state, delta) => {
    angle -= 0.01
    spotlight1.current.position.x = 2*Math.sin(angle)
    spotlight1.current.position.y = 2*Math.cos(angle)
    spotlight2.current.position.x = 2*Math.cos(angle)
    spotlight2.current.position.y = 2*Math.sin(angle)
    
    //console.log(spotlight1.current.position)
    
   })


  return (
    <group ref={group} {...props} dispose={null}>
      <spotLight ref={spotlight1} position={[0,0.25,0.5]} intensity={1} penumbra={1} angle={0.53} lookAt={[0,0,0]} color="#FEDD00" />
      <spotLight ref={spotlight2} position={[0,0.25,-0.5]} intensity={1} penumbra={1} angle={0.53} lookAt={[0,0,0]} color="#FEDD00" />
      <spotLight ref={spotlight3} position={[0.5,0.1,0.5]} intensity={2.5} penumbra={1} angle={0.35} color="#FEDD00"/>
      {/* <directionalLight ref={directionalLight} castShadow lookAt={[0,0,0]} intensity={1} position={[0.2,2,0.2]}/> */}
      {/* <rectAreaLight position={[-0.1,0.5,0.1]} width={1} height={1} intensity={50} lookAt={[0,0,0]} rotation={[0,Math.PI,0]}/> */}
      <Html scale={0.01} rotation={[0, -3*Math.PI / 4 + 0.5, 0]} position={[-0.26,0.1,0.05]} transform occlude>
          <About 
          onClick={() => {
            console.log(props.aboutStatus)
            props.setAboutStatus(!props.aboutStatus)}}
          variants={containerVariants}
          animate={props.aboutStatus ? "hidden" : "visible"}>
            About <span style={{fontSize: '1em' }}>🥲</span>
          </About>
      </Html>

      <Html scale={0.01} rotation={[0, -Math.PI / 2 +0.5, 0]} position={[-0.26,0.1,-0.01]} transform occlude>
          <FAQ 
          onClick={() => {
            console.log(props.aboutStatus)
            props.setAboutStatus(!props.aboutStatus)}}
          variants={containerVariants}
          animate={props.aboutStatus ? "hidden" : "visible"}>
            FAQ <span style={{fontSize: '1em' }}>🥲</span>
          </FAQ>
      </Html>

      <Html scale={0.01} rotation={[0, -3*Math.PI / 4 +0.5, 0]} position={[-0.20,0.1,0.05]} transform occlude>
          <Team 
          onClick={() => {
            console.log(props.aboutStatus)
            props.setAboutStatus(!props.aboutStatus)}}
          variants={containerVariants}
          animate={props.aboutStatus ? "hidden" : "visible"}>
            Team <span style={{fontSize: '1em' }}>🥲</span>
          </Team>
      </Html>

      <Html scale={0.01} rotation={[0, -Math.PI / 2 +0.5, 0]} position={[-0.19,0.1,0.00]} transform occlude>
          <Roadmap 
          onClick={() => {
            console.log(props.aboutStatus)
            props.setAboutStatus(!props.aboutStatus)}}
          variants={containerVariants}
          animate={props.aboutStatus ? "hidden" : "visible"}>
            Roadmap <span style={{fontSize: '1em' }}>🥲</span>
          </Roadmap>
      </Html>
      {/* <primitive object={nodes.mum_rpmlet_midres_rig_mastermum_rpmlet_rig} />
      <group name="theo_dad_root" position={[0, 0, -0.37]}>
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_gum_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_gum_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_gum_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth01_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth02_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth03_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth04_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth05_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth06_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth07_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth08_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth09_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth10_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth11_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth12_up"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_up.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_up.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_gum_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_gum_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_gum_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth01_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth02_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth03_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth04_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth05_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth06_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth07_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth08_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth09_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth10_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth11_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_teeth_tooth12_dwn"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_dwn.geometry}
          material={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_dwn.material}
        />
        <mesh
          name="Teethdad_hires_mod_mouth_tongue"
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_tongue.geometry}
          material={nodes.Teethdad_hires_mod_mouth_tongue.material}
        />
        <mesh
          name="theo_dad_hat_01"
          castShadow
          receiveShadow
          geometry={nodes.theo_dad_hat_01.geometry}
          material={nodes.theo_dad_hat_01.material}
        />
        <mesh
          name="theo_dad_hat_05"
          castShadow
          receiveShadow
          geometry={nodes.theo_dad_hat_05.geometry}
          material={nodes.theo_dad_hat_05.material}
        />
        <mesh
          name="theo_dad_hat_06"
          castShadow
          receiveShadow
          geometry={nodes.theo_dad_hat_06.geometry}
          material={nodes.theo_dad_hat_06.material}
        />
        <mesh
          name="theo_dad_hat_07"
          castShadow
          receiveShadow
          geometry={nodes.theo_dad_hat_07.geometry}
          material={nodes.theo_dad_hat_07.material}
        />
        <mesh
          name="theo_dad_hat_02"
          castShadow
          receiveShadow
          geometry={nodes.theo_dad_hat_02.geometry}
          material={nodes.theo_dad_hat_02.material}
        />
        <group name="theo_dad_cape" position={[0.09, 0, 0.4]} rotation={[-0.47, 0.21, 0.63]}>
          <mesh
            name="theo_dad_cloak_01"
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_cloak_01.geometry}
            material={nodes.theo_dad_cloak_01.material}
          />
        </group>
      </group> */}
      <PerspectiveCamera
        name="camera2"
        makeDefault={false}
        far={10000}
        near={0.01}
        fov={81.2}
        position={[0.04, 0.08, 0.36]}
        rotation={[0, 0.11, 0]}
      />
      {/* <mesh
        name="Cape6"
        castShadow
        receiveShadow
        geometry={nodes.Cape6.geometry}
        material={nodes.Cape6.material}
        position={[0, 0.09, -0.03]}
        scale={4.53}
      />
      <mesh
        name="Theo3_Theo_Legs13"
        castShadow
        receiveShadow
        geometry={nodes.Theo3_Theo_Legs13.geometry}
        material={nodes.Theo3_Theo_Legs13.material}
      /> */}
      {/* <mesh
        name="Fire_01"
        castShadow
        receiveShadow
        geometry={nodes.Fire_01.geometry}
        material={nodes.Fire_01.material}
        position={[-0.04, 0.17, -0.22]}
        rotation={[Math.PI / 2, 0, 0.25]}
        scale={[81.7, 5.11, 45.95]}
      />
      <mesh
        name="Fire_02"
        castShadow
        receiveShadow
        geometry={nodes.Fire_02.geometry}
        material={nodes.Fire_02.material}
        position={[-0.29, 0.27, -0.25]}
        rotation={[-Math.PI / 2, 0, -1.92]}
        scale={[84.57, 6.51, -58.62]}
      />
      <mesh
        name="Fire_03"
        castShadow
        receiveShadow
        geometry={nodes.Fire_03.geometry}
        material={nodes.Fire_03.material}
        position={[0.14, 0.19, -0.25]}
        rotation={[Math.PI / 2, 0, 0.19]}
        scale={[72.54, 4.62, 38.25]}
      />
      <mesh
        name="Fire_04"
        castShadow
        receiveShadow
        geometry={nodes.Fire_04.geometry}
        material={nodes.Fire_04.material}
        position={[0.25, 0.19, -0.25]}
        rotation={[Math.PI / 2, 0, 0.54]}
        scale={[71.99, 4.5, 57.45]}
      />
      <mesh
        name="Fire_05"
        castShadow
        receiveShadow
        geometry={nodes.Fire_05.geometry}
        material={nodes.Fire_05.material}
        position={[0.01, 0.14, -0.06]}
        rotation={[Math.PI / 2, 0, 0.08]}
        scale={[72.59, 3.92, 35.31]}
      /> */}
      {/* <mesh
        name="pSphere1"
        castShadow
        receiveShadow
        geometry={nodes.pSphere1.geometry}
        material={nodes.pSphere1.material}
        position={[0, 10.46, 0]}
        scale={1102.3}
      /> */}
    </group>
  )
}

useGLTF.preload('/Theo_all_06.glb')

const About = styled(motion.div)`
  cursor: pointer;
  outline: none;
  border: none;
  font-size: 8px;
  font-weight: 300;
  background: black;
  color: #f0f0f0;
  padding: 2px 10px;
  border-radius: 20px;
  letter-spacing: 1px;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 10px;
  z-index: 1;
`

const FAQ = styled(About)`
`

const Team = styled(About)`
`
const Roadmap = styled(About)`
`

const containerVariants = {
  hidden: { 
    scale: 0,
    opacity: 0,
  },
  visible: {
    scale: 1,
    opacity: 1,
    transition: {
      duration: 1, type: 'spring', stiffness: 120
    }
  }
}